### PR TITLE
Add Table of Contents (ToC) to Code of Conduct (CoC)

### PR DESCRIPTION
**Pull request by KyleMit**
We can merge against other changes to the CoC, but this should help navigate to particular sections of of the code of conduct since it's pretty long.  

Also gives each header element a unique id - so we can build fragment urls and link directly to them.

### CODE REVIEW

**Comment by zekefarwell** [comment]
This looks great!  Super cool to generate the table of contents from the headings in the markdown document.  Looks like you resolved or worked around the the array sorting bug?  

The only comment I have is that the table of contents items don't look like links until you hover over them (or tap them on a touch screen).  I can see why you removed the default link underlines (box-shadow/border) as it looks a bit too chunky in a list like this.  Perhaps thinner underlines or more line spacing would look better.


**Default link underlines with current spacing**
Screen Shot 2019-07-29 at 9 55 56 AM

**Thinner link underlines with more spacing**
Screen Shot 2019-07-29 at 10 05 19 AM

**Comment by KyleMit** [comment]
> I can see why you removed the default link underlines (box-shadow/border) as it looks a bit too chunky in a list like this.

Exactly this.  

I like your solution of thinning them out better than mine of removing them all together.  Wanna push it?

**Review by zekefarwell — APPROVED** [review]

**Comment by zekefarwell** [comment]
I was just messing around in browser dev tools for a quick screenshot, but yeah if like the way that looks I'll push up a change to this branch.

**Comment by KyleMit** [comment]
> Looks like you resolved or worked around the the array sorting bug?

[Submitted a PR](https://github.com/jdsteinbach/eleventy-plugin-toc/pull/4) to fix it, but it doesn't look like the lib is in active maintenance, and it would take a while for anything to bubble into a release against npm (since we have a remote build system, it enforces good practices of every dependency *needing* to be in npm)

I actually just switched from [jdsteinbach/eleventy-plugin-toc](https://github.com/jdsteinbach/eleventy-plugin-toc) to [JordanShurmer/eleventy-plugin-toc](https://github.com/JordanShurmer/eleventy-plugin-toc), which is a fork of the original, but looks more actively maintained, has better documentation, and doesn't have the sort bug.  

image

**Pull request merged**
