### PR TITLE
Use horizontal symbiotic labs logo

### PR DESCRIPTION
**Pull request by benglass**
@KyleMit Hi Kyle! Just requesting a swap to use symbiotic's horizontal logo, thanks much!

## before

image

## after

image

### CODE REVIEW

**Comment by zekefarwell** [comment]
Looks great, @benglass.  Thanks for the PR!

**Comment by KyleMit** [comment]
@zekefarwell, I'm taking a stab at formalizing our contribution guidelines (I'll pop open another PR in a bit). I ran the logo through [svgomg](https://jakearchibald.github.io/svgomg/), but was trying to figure out how to add a commit to a downstream branch that we don't own (`symbioticlabs:symbiotic-logo-change` ) in order to update the PR prior to merging.  

What we'd ideally like to do is allow upstream maintainers to push to downstream forks with permissions. 

These github articles outline the basic premise:

* [Allowing changes to a pull request branch created from a fork](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [Committing changes to a pull request branch created from a fork](https://help.github.com/en/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork)

Also, it looks like installing the [`hub cli`](https://github.com/github/hub) can also help maintainers work on forked repos without having to clone a whole new repo.

**Comment by zekefarwell** [comment]
@KyleMit sorry I didn't realize you were already working on this.  I just saw it and looked good so I merged it.  Did another commit to master after the fact with an optmized version of the new svg https://github.com/vtcodecamp/2019.vtcodecamp.org/commit/f7515649a827059f265c5374b1972373dbd87d1a

**Comment by KyleMit** [comment]
@zekefarwell - sa'll good.  I knew we *could* get there eventually, but was wanted to prove to myself that it was possible to update a PR prior to merging

@benglass - thanks for the updated logo.  Looks much more consistent with other logos in that area. I wonder if we should solicit multiple aspect ratios from sponsors if they have a set of logos just to make it easier to maintain consistent visual weight in each category

**Pull request merged**
