### PR TITLE
Add CoC link to top nav

### PR DESCRIPTION
**Pull request by mmcelaney**
Making CoC more prominent on the site

### CODE REVIEW

**Comment by KyleMit** [comment]
I really like the idea of promoting this more heavily.  

We probably just want to tweak our responsive layout a little so it looks a little nicer on mobile.  We had originally spent a lot of time with the copy so that on mobile it was as small as possible and didn't have to wrap.



Another idea would be to have it be a banner on the top of the page - **[Read our code of conduct]** - and it would only go away once you clicked on it

**Review by robhalevt — APPROVED** [review]

**Comment by robhalevt** [comment]
> Another idea would be to have it be a banner on the top of the page - **[Read our code of conduct]** - and it would only go away once you clicked on it

I like this idea if the responsive layout can't be modified. I'm not sure the level of effort to do that, though.

**Comment by KyleMit** [comment]
I pushed some minor updates so the layout would look a little more natural on small screens, and condensed text even more on super small screens.  In either case, it wasn't a material problem that would need to hold up pushing content changes, but I think they layout works well at this point

**Comment by zekefarwell** [comment]
I think with the adjustments @KyleMit made this works well enough for now as it only wraps on the smallest phone screens.  I'd say go ahead and merge it.

We do need to come up with a way to handle more nav items soon though.  We're going to have Sessions and Speakers to add, and then the Schedule when that's ready.  Perhaps the Diversity and Parking pages should be in the main nav too?  We'll probably need some sort of expanding and collapsing menu for the smallest screens.

**Review by zekefarwell — APPROVED** [review]

**Pull request merged**
